version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
  test-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123456
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: nest-iluvcoffee
